### ISSUE TITLE
Random shows user id instead of name. 

### ISSUE THREAD

**Issue by Akirtovskis** [cool-bots/doge-cool#23]
E.g when someone calls `random` this is what shows up :  "Much luck @12837USD, wow you..."

**Comment by a-w-e-s-o-m-e** [comment]
@Akirtovskis up to fix it? You can create a dev environment by creating a free slack environment... https://slack.com/get-started

**Comment by Akirtovskis** [comment]
Can I do this w/o blockio keys?

**Comment by a-w-e-s-o-m-e** [comment]
You could mock the calls to the API... just comment the lines of code where block.io is called or replace the function :)
